apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{deploy_name}}
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{deploy_name}}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
---
