apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    application: {{application_name}}
    build: "{{build_id}}"
    type: "application"
    bamboo_deploy_release: "{{bamboo_deploy_release}}"
    bamboo_deploy_project: "{{bamboo_deploy_project}}"
  name: {{deploy_name}}
  namespace: {{namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      application: {{application_name}}
      build: "{{build_id}}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: {{application_name}}
        build: "{{build_id}}"
        type: "application"
        bamboo_deploy_release: "{{bamboo_deploy_release}}"
        bamboo_deploy_project: "{{bamboo_deploy_project}}"
    spec:
      containers:
      - image: {{image}}
        imagePullPolicy: Always
        name: {{deploy_name}}
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 5
          timeoutSeconds: 5
          successThreshold: 2
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          failureThreshold: 3
          timeoutSeconds: 1
          successThreshold: 1
        env:
          - name: GIT_REPO
            value: {{git_repo}}
          - name: SSH_KEY
            value: {{ssh_key}}
          - name: NEW_RELIC_LICENSE_KEY
            value: {{NEW_RELIC_LICENSE_KEY}}
        resources:
          requests:
            cpu: 100m #1000m = 1 cpu core
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
