apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{application_name}}
  namespace: {{namespace}}
  annotations:
    # enable kube-lego for this ingress
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - "{{hostname}}"
    secretName: {{hostname}}
  rules:
  - host: {{hostname}}
    http:
      paths:
      - backend:
          serviceName: {{application_name}}
          servicePort: 80
        path: /
---
