apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{application_name}}
  namespace: {{namespace}}
  annotations:
    # enable kube-lego for this ingress
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    # nginx params
    nginx.org/client-max-body-size: "100m"
    nginx.org/http2: "true"
    nginx.org/hsts: "true"
    nginx.org/hsts-max-age: "2592000"
    nginx.org/hsts-include-subdomains: "true"
    nginx.org/server-tokens: "false"
spec:
  tls:
  - hosts:
    - "{{hostname}}"
    secretName: {{hostname}}
  rules:
  - host: {{hostname}}
    http:
      paths:
      - backend:
          serviceName: {{application_name}}
          servicePort: 80
        path: /
---
