apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{application_name}}-clinics
  namespace: {{namespace}}
  annotations:
    # enable kube-lego for this ingress
    kubernetes.io/tls-acme: "false"
    kubernetes.io/ingress.class: "nginx"
    # nginx params
    nginx.org/client-max-body-size: "100m"
    nginx.org/http2: "true"
    nginx.org/hsts: "true"
    nginx.org/hsts-max-age: "15638400"
    nginx.org/hsts-include-subdomains: "true"
    nginx.org/server-tokens: "false"
spec:
  tls:
  - hosts:
    - "{{hostname}}"
    secretName: {{cert}}
  rules:
  - host: "{{hostname}}"
    http:
      paths:
      - backend:
          serviceName: "{{application_name}}-{{build_id}}"
          servicePort: 80
        path: /
---
