apiVersion: v1
kind: Service
metadata:
  name: {{application_name}}
  namespace: {{namespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    application: "{{application_name}}"
    build: "0"
  sessionAffinity: None
---
